### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by yasserhussain1110** [BharatiVinod/city-cricket-app#4]
Please rename project so that it does not have any underscore.
```cric_match``` does not look good. 

It will be better if it is something like 
```cricket-match```
or
```cricket-match-app```
something like that.

**Comment by yasserhussain1110** [comment]
@BharatiVinod Do you have a problem with full names?

`city-cric-app` could be `city-cricket-app`  :smile:

**Comment by BharatiVinod** [comment]
Mr. Yasser I have fixed the issue, If you're ok this, please close the issue if not, please mention it, I will fix...
Thank you

**Comment by BharatiVinod** [comment]
Yes I have changed it as city-cricket-app...Thank you sir

**Comment by yasserhussain1110** [comment]
Great. Thanks :+1:
